#
# MM30 v7.2 configuration
#

# seed
random_seed: 123

# plot colors
colors: ["#00AFBB", "#E7B800", "#FC4E07", "#BB3099", "#EE0099", "#0000AC"]
stage_colors: ["#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3"]

# survival plot upper/lower percentil cutoff choices
surv_cutoff_opts: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

# score filtering; maximum number of missing datasets allowed
scores_max_missing_datasets:
  disease_stage: 6
  surv_os: 3
  surv_pfs: 2
  treatment_response: 2

# dataset expr previews
preview_num_genes: 512

# when generating dataset preview plots, genes missing in greater than the specified number of
# samples (for all datasets) are filtered out prior to subsampling
preview_max_missing_samples: 0
